### PR TITLE
Add fixed to make bold text render properly from google font and darker overall

### PR DESCRIPTION
**Pull request by blanchardjeremy**

### CODE REVIEW

**Comment by beshaya** [comment]
I think @gyp replaced Lato with LatoLocal because Lato is broken for some non english languages. Let's make sure we don't break our friends across the ocean!

**Review by gyp — CHANGES_REQUESTED** [review]
Yep, that is correct, that's why I did that, see 6b75cd70  I'd prefer to keep it if possible, but, truth be told, the difference is minor and mostly only annoys me out of pedantry. I'd rather we kept it, but I can live with reverting back to the older font version that's available in Google Fonts. If we do that, however, we should remove the custom fonts I added under src/fonts.

**Comment by blanchardjeremy** [comment]
Yeah, I think we just need to add the font files for bold and it should work. I'll work on it this weekend.

**Comment by blanchardjeremy** [comment]
Replaced by #734

**Pull request closed without merging**
