### PR TITLE
Remove copy to spreadsheet button

### PR DESCRIPTION
**Pull request by blanchardjeremy**
No longer needed. It was only a stopgap measure before we had automatic prevalence data imports.

### CODE REVIEW

**Comment by beshaya** [comment]
Do we have a good way to communicate that folks using old sheets need to
upgrade to one with auto-importing?

**Comment by blanchardjeremy** [comment]
@beshaya good question. It was only ever designed to work with a manual data entry for a very certain version of the spreadsheet. I don't think it works with old versions before that. So... *shrug* I'm assuming almost nobody uses it. But I don't have the data to back that up. And there's a chance I could be mis remembering.

Would you suggest we add a little notice for spreadsheet users for a while to encourage them to switch to the latest version?

**Comment by beshaya** [comment]
> @beshaya good question. It was only ever designed to work with a manual data entry for a very certain version of the spreadsheet. I don't think it works with old versions before that. So... _shrug_ I'm assuming almost nobody uses it. But I don't have the data to back that up. And there's a chance I could be mis remembering.
> 
> Would you suggest we add a little notice for spreadsheet users for a while to encourage them to switch to the latest version?

Yeah, could we keep this button for, say, 2 weeks, and have it pop up a warning to upgrade?

**Comment by beshaya** [comment]
ALSO WE SHOULD ADD ANALYTICS TO THAT BUTTON

**Comment by blanchardjeremy** [comment]
Oops. Didn't mean to close this.

**Comment by blanchardjeremy** [comment]
@beshaya ready for your review.

**Review by beshaya — APPROVED** [review]

**Pull request merged**
