### PR TITLE
Add python formatter

### LINKED ISSUE #1030: Add python formatter
We only have one (main) python file, but we don't have a workspace-wide config file for it, so it keeps

Steps:

1. Pick a linter
2. Add a config file for it
3. Add the lint run to `yarn lint` and `yarn fix`

Bonus: 
- Make sure that VSCode automatically picks up the linter we're using

### PR DESCRIPTION
**Pull request by blanchardjeremy**
* Fixes #1030 

Turns out i actually meant "formatter" not "linter" when I opened the issue.

### CODE REVIEW

**Comment by beshaya** [comment]
I'm vaguely surprised by how little this changed the file. Perhaps we want a more opinionated formatter like Black or YAPF?

https://blog.frank-mich.com/python-code-formatters-comparison-black-autopep8-and-yapf/

**Comment by oxytocinlove** [comment]
I'm in favor of Black, we use it at work

**Comment by blanchardjeremy** [comment]
> I'm in favor of Black, we use it at work

Awesome. Do you have any default config you like? That'd help this move forward. I'm way out of my familiar territory on setting this up. So if you either have a config file you can share or if you just wanna take over this PR, I welcome it. :)

**Comment by oxytocinlove** [comment]
yeah happy to just take over this issue :)

**Comment by jaraco** [comment]
Superseded by #1120.

**Pull request closed without merging**
