### PR TITLE
Internationalization & Hungarian translation

### PR DESCRIPTION
**Pull request by gyp**
I created a localized version using i18next that covers the Calculator and the About page. There are a few glitches here & there, but its usable. I've included a Hungarian translation as well.

I know it's a major patch which makes ongoing maintenance and all subsequent improvements more difficult. At this moment it is optimized to be minimally obtrusive to the main branch and potentially be maintained as a fork long-term: the keys for the translations are the English labels themselves. Let me know your thoughts on merging this to the master. If you'd like to do that and you agree that it's the best choice, I'd be happy to extract the English labels into separate language files, which is probably easier to maintain in the long term if all languages are upstream. If you don't want to take on that burden, that's fine as well, I'll just try to maintain the fork myself and publish it separately.

### CODE REVIEW

**Comment by gyp** [comment]
So, what do you folks think? Would you entertain the idea or should I go ahead and prepare for maintaining & publishing the fork for the long term?

It's not a problem either way, I just want to avoid duplicate work.

/cc @catherio @dominic @beshaya as the most active contributors

**Review by beshaya — CHANGES_REQUESTED** [review]
Hi @gyp, sorry for the delay. We absolutely love this and want to support it.

Could you go ahead and clean up the english labels?

Thank you so much for this huge piece of work!

**Comment by gyp** [comment]
Sounds good! I'll get to it and let you know when it's ready to be merged. Will probably take about a week or so, depending on how much free time I'll have, we'll see.

**Comment by gyp** [comment]
OK, I think I'm done with what needed to be done at this stage. The only big chunk that's left over is the localization of the country/location selector, but that'd need touching too many parts of the code, so I did not dare to go there -- and it might not even be worth doing. Let me know what you think, @beshaya

**Comment by beshaya** [comment]
Hi Gyp, sorry I've been hammered with work this week + out for the weekend. I'll take a look early next week.

Thanks again for this!

**Comment by blanchardjeremy** [comment]
@gyp  - Thanks for all you're doing here. I've been tracking this thread along with @beshaya and the rest of the team. 

One question I/we are looking at is how to bring these changes in alongside the very large project happening over on the ux-redesign branch. We may request your help in merging your work with the numerous updates happening over there. I hate to create more work for you. Once these two branches are both merged into main, things should be pretty easy moving forward.

@beshaya / others - curious your thoughts which one we should merge first. Or if @gyp should potentially start working against ux-redesign now and tracking it as we go?

**Comment by gyp** [comment]
Sure, I'm happy to help, let me know which way would you like me to proceed.

I might need some help here & there though, I am by no means proficient in React, Typescript and the last time I worked on anything frontend-heavy as a coder was a decade ago. But I'll try and will ask for help if I'm stuck :)

**Comment by blanchardjeremy** [comment]
@gyp Thanks again for all your work. We want you to know how much we appreciate it! We've been hard at work with a big upgrade. We hope to have it out in the next week.

Whenever you're ready, you might start doing your work against the ux-redesign branch. There will be a ton of merge conflicts with the work you already did that will need to be resolved because there is so much new text on the calculator page. As soon as we merge ux-redesign into main, I'm in favor of supporting you to get your i18n branch in next. (I haven't talked with @beshaya or others directly about a plan, this is just my two cents.)

So yeah. If you merge in ux-redesign, that's where to begin, I think!

**Comment by gyp** [comment]
OK, I started working on it. It's indeed a huge merge with tons of conflicts, but I'll work through those one-by-one. I'll let you know when it's done. (I dig the new design, BTW :))

**Comment by blanchardjeremy** [comment]
Glad you like the new design. And thanks! I was thinking of you every time I made a commit and I was like "this is making a lot of work for him!" I appreciate your diligence! Once we get your branch merged in, it'll be easier for all of us to keep it up to date.

**Comment by gyp** [comment]
OK, the big-bang merge is now done, it wasn't that horrible after all.
But there are tons of small things yet to be done, I'll let you know when it will make sense to look at it again.

**Comment by gyp** [comment]
I think it's now ready to be merged.

The ux-design branch as of afde36383707a2dee5941605739f5e3ae501d4c0 is now merged and the localization is fairly complete. There are still a few rough edges here & there but I think it's acceptable.

Please do check the functionality and all the labels, especially around the changes you made recently as there were a few brutal conflicts and I could easily have messed up the merges.

/cc @blanchardjeremy

**Comment by blanchardjeremy** [comment]
@beshaya @gyp - I think we need to recreate this pull request with a request to merge into ux-redesign. Is that right?

Right now it includes all the commits from ux-redesign which makes the code review very difficult. 7

**Comment by blanchardjeremy** [comment]
I did a review of the calculator page and here are my notes:

- "Step 2 - Person Risk" (purple header) should be "Step 2: Describe the activity"
- "Duration:How long is the activity, in minutes?" is missing a space before "How"
- Under the small help text underneath "Their Mask" it looks like you changed it to _If they're eating or drinking, select “no mask”_ ... It should be _If you're_
- the points display should show: "90% of *your* weekly risk budget" (the word "your" is missing)
- "We believe with roughly 90% confidence that *th* actual risk falls " (type. should be *"the"*)
- " If you do this activity many times with the same people each week, enter it as "household member" to see what the maximum transmission rate is per week." doesn't match what I see on the ux-redesign branch. Check it out.
- Typo: "*Hight* Caution Budget"

**Comment by gyp** [comment]
I changed  the pull request to reflect that I want to merge it into ux-redesign. Most of the conversation here was generic, so it would not make sense to start a completely new pull request just because of that.

Thanks for the review! Those exactly the kind of problems I thought I'd leave in it. 

> * "Step 2 - Person Risk" (purple header) should be "Step 2: Describe the activity"
> * "Duration:How long is the activity, in minutes?" is missing a space before "How"
> * the points display should show: "90% of _your_ weekly risk budget" (the word "your" is missing)
> * "We believe with roughly 90% confidence that _th_ actual risk falls " (type. should be _"the"_)
> * Typo: "_Hight_ Caution Budget"

All fixed by d70c173294d6152675470b191205afc67843168e

> * Under the small help text underneath "Their Mask" it looks like you changed it to _If they're eating or drinking, select “no mask”_ ... It should be _If you're_

Oh yeah, I wanted to commit that one separately as that was not a mere localization rather a substantive change, I just forgot by the time I got there. Sorry about that. Let me know if you'd like me to extract it to a separate patch or simply revert it.

But please double check it first though, as I think the original version was incorrect and my change makes sense. Why should _my_ eating nullify _their_ mask use? It nullifies my own mask use all right, but that's already taken care of by setting my mask usage to 'no mask'. If they're eating, it cancels out their mask usage, but if they're wearing their mask, that protects me, even if I took mine off while I'm eating.

> * " If you do this activity many times with the same people each week, enter it as "household member" to see what the maximum transmission rate is per week." doesn't match what I see on the ux-redesign branch. Check it out.

That was a deliberate simplification. The ux-redesign branch there does this strange thing where it gives the suggestion either as 'household member' or 'partner/spouse' based in whether a distance is chosen in the selector:
https://github.com/microcovid/microcovid/blob/1202d71baa182513521d1116bac96b25bc2feb8d/src/components/calculator/ExplanationCard/ExplanationCard.tsx#L173-L180 I don't understand the logic behind it (why would the lack of selecting a distance suggest household member and selecting any kind of distance a partner?), and I don't think such a level of precision or brevity is required for a note hidden pretty far down in the page structure. On the other hand, the code and the translation would be much more complex if one had to accommodate for this branching, so I thought just adjusting the verbiage slightly and removing this logic is the better choice here.

**Comment by gyp** [comment]
I just merged in the latest changes from ux-redesign and noticed that the budget selector is broken, and it seems to be broken on ux-redesign as well: changing the budget does not update the risk results and the thermometer. I tried to figure out what's going on but my React skills are way too limited to troubleshoot this, I just thought you'd like to know, as this pretty much breaks the budget setting functionality.

**Comment by gyp** [comment]
It's great to see the redesigned merged onto the mainline. Thanks for the housekeeping, @beshaya.
I merged in the changes to this branch again, as of this moment, it merges clean onto main, too.
I kept the changes mentioned in https://github.com/microcovid/microcovid/pull/284#issuecomment-719903795 (change in the note about the effect of others mask wearing during eating and a simplification around the note on the ExplanationCard), let me know what you think about those.

**Comment by blanchardjeremy** [comment]
@gyp  Thanks for the questions/suggestions on those two points above.

For this PR, I think it's important that we match whatever is in the current app exactly (even if there are spots for improvement, as you suggest). For any suggestions/bugs you find, please open them as separate issues and just "leave them there" for now so this pull request can be as simple as possible. 

You can just copy-paste the comments from above into two separate issues and we can all look at them together.

And yeah, feel free to just make a new commit "reverting" those changes. (and you can keep them around for separate PRs.

**Comment by gyp** [comment]
@blanchardjeremy there you go, they're reverted, a separate issue was filed under #457 

Note that I made the required follow-ups in the PointsDisplay functional tests as well, even though they did not break yet, but they would, should any changes be made in the labels in the default locale. It made that code quite hard to read, which is not ideal, but, not being a React developer, I've got no idea what would be the right strategy around that.

**Comment by blanchardjeremy** [comment]
@gyp FYI - we're looking at getting this merged in today or in the next day or so. From then on out, each pull request should be a small "bite-sized" piece of code that can be easily reviewed.

**Comment by gyp** [comment]
That's awesome, thanks.

Do you have any plans to add new translations? I'll try to recruit people to help out, but I want to avoid double work.

**Pull request merged**
