### PR TITLE
Compare total risk to risk budget.

### PR DESCRIPTION
**Pull request by beshaya**
image

image

Fixes: #204

### CODE REVIEW

**Comment by linesarefuzzy** [comment]
As a user, just stumbling on this PR, I like the idea a lot, but I suggest adding it to the existing annual risk language rather than replacing it. I like seeing the annualized risk too.

**Comment by catherio** [comment]
🤷‍♀️  I'm open to including both

**Comment by beshaya** [comment]
Added the annualized risk back. I don't like the additional clutter, personally.

**Comment by catherio** [comment]
agree, don't prefer the clutter. revert 7d6b55b and I'll LGTM?

**Comment by beshaya** [comment]
@catherio Done

**Review by catherio — APPROVED** [review]
LGTM

**Pull request merged**
