### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/microcovid/microcovid/) for microCOVID/microCOVID.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by gyp** [comment]
Weblate's acting up again, please merge #538 instead of this and I'll reset it again.

**Comment by gyp** [comment]
@blanchardjeremy this branch has now accumulated a nice chunk of translations, could you merge it in please. It'd make it possible to add the Czech translation which seems complete by now and only needs a final review.

**Comment by blanchardjeremy** [comment]
@gyp happy to. Do you want me to merge #538  or this one?

**Comment by gyp** [comment]
Please merge this one, #538 was just needed as a one-off cleanup. I've got into the habit of locking things on Weblate during these merge windows, hopefully we'll be able to avoid conflicts this way.

**Comment by blanchardjeremy** [comment]
Merged!

**Pull request merged**
