### PR TITLE
feat: update prevalence to March 2021

### PR DESCRIPTION
**Pull request by josiah-roberts**
covid19-projections.com released [a model update](https://covid19-projections.com/estimating-true-infections-revisited/) in March, 2021 which we never picked up.

This PR updates the prevalence model to match that model, both in web and `update_prevalence.py`.

### CODE REVIEW

**Comment by justinhaaheim** [comment]
Seems legit. @beshaya can you take a look?

**Review by beshaya — APPROVED** [review]

**Comment by apiology** [comment]
@beshaya: will a matching change be needed in the Risk Tracker spreadsheet?

(I'll deal with the codecov check failure either way - will be a good opportunity to convince the prevalence script to be more testable)

**Comment by apiology** [comment]
Another potential update area: https://www.microcovid.org/paper/7-basic-method#step-two-underreporting-factor

**Comment by apiology** [comment]
Ah, I see, the changes to `update_prevalence.py` are the code path that updates the .CSV files with this information.

**Review by apiology — APPROVED** [review]
Thanks so much for the update, @josiah-roberts!  Really appreciate the legwork you did to make this happen.

**Pull request merged**
