### PR TITLE
Default the total population to 100k and positivity to 10%

### PR DESCRIPTION
**Pull request by jaraco**
Ref #1826

### CODE REVIEW

**Comment by jaraco** [comment]
Due to #1828, retargeting to `main`.

**Review by apiology — COMMENTED** [review]
I don't really know enough to comment on the code being sufficient without testing personally, but this certainly seems a simple way to do it (too simple? idk). 

I'd defer to @octern's testing for the final OK.

**Comment by octern** [comment]
LGTM. Looks like this only has an effect if the user doesn't have a stored value, which is fine.

**Review by octern — APPROVED** [review]
LGTM, should fail gracefully if the user has any values saved.

**Pull request merged**
