### PR TITLE
RFC: discuss vaccine protection from severe COVID

### LINKED ISSUE #837: Q&A: Vaccine protection against severe covid at odds with available evidence?
Microcovid's Q&A suggests that vaccine protection against severe covid (hospitalization or death) is below 100%:

https://github.com/microcovid/microcovid/blob/c6ea542cd401c83e3b71ab28a554464dd3333937/src/posts/paper/13-q-and-a.ts#L215

Is this significantly at odds with the available evidence? For example, [Wikipedia](https://en.wikipedia.org/w/index.php?title=COVID-19_vaccine&oldid=1019606401) lists 100% protection against death or hospitalization for every vaccine, with the possible exception of CoronaVac (ie. Sinovac).
Wiki_covid_efficacy

[COVID-19 Vaccine AstraZeneca confirms 100% protection against severe disease, hospitalisation and death in the primary analysis of Phase III trials.](https://www.astrazeneca.com/media-centre/press-releases/2021/covid-19-vaccine-astrazeneca-confirms-protection-against-severe-disease-hospitalisation-and-death-in-the-primary-analysis-of-phase-iii-trials.html)

Links to the evidence in question:
[Moderna](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e0651c7a-2fe2-459d-a766-0d59e919f058)
[Pfizer](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=908ecbe7-2f1b-42dd-94bf-f917ec3c5af8)
AstraZeneca [one](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7894131) [two](https://www.astrazeneca.com/content/astraz/media-centre/press-releases/2021/azd1222-us-phase-iii-primary-analysis-confirms-safety-and-efficacy.html)
[J&J](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14a822ff-f353-49f9-a7f2-21424b201e3b)

### PR DESCRIPTION
**Pull request by TheSven73**
Is the following statement in Q&A still in agreement with the available
scientific evidence and consensus?

> Data from Israel's study suggests that Pfizer's vaccine reduced
> cases of severe COVID by 92%, about the same as the reduction in
> mild/asymptomatic COVID. Therefore we do not think that mRNA vaccines
> reduce the chance of hospitalization or death beyond the reduction
> in contracting COVID in the first place. It is possible that the
> traditional vaccines (AstraZenica, Johnson&Johnson) are somewhat more
> protective againt severe COVID than mild COVID, but we have not seen
> compelling data for this.

If not, should it be tweaked or removed?

For example, [Wikipedia](https://en.wikipedia.org/w/index.php?title=COVID-19_vaccine&oldid=1019606401)
lists 100% protection against death or hospitalization for every vaccine,
with the possible exception of CoronaVac (ie. Sinovac).
Wiki_covid_efficacy

Links to the evidence in question:
[Moderna](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e0651c7a-2fe2-459d-a766-0d59e919f058)
> Severe COVID-19 symptoms observed in the Moderna vaccine trials, were defined as symptoms having
> met the criteria for mild/moderate symptoms plus any of the following observations: Clinical signs
> indicative of severe systemic illness, respiratory rate ≥30 per minute, heart rate ≥125 beats per minute,
> SpO2 ≤93% on room air at sea level or PaO2/FIO2 <300 mm Hg; or respiratory failure or ARDS,
> (defined as needing high-flow oxygen, non-invasive or mechanical ventilation, or ECMO), evidence
> of shock (systolic blood pressure <90 mmHg, diastolic BP <60 mmHg or requiring vasopressors); or
> significant acute renal, hepatic, or neurologic dysfunction; or admission to an intensive care unit
> or death. No severe cases were detected for vaccinated individuals in the trials, compared with 30
> severe cases reported in the placebo group (incidence rate 9.1 per 1000 person-years).

AstraZeneca [one](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7894131) [two](https://www.astrazeneca.com/content/astraz/media-centre/press-releases/2021/azd1222-us-phase-iii-primary-analysis-confirms-safety-and-efficacy.html)
> 100% efficacy against severe or critical disease and hospitalisation
[COVID-19 Vaccine AstraZeneca confirms 100% protection against severe disease, hospitalisation and death in the primary analysis of Phase III trials.](https://www.astrazeneca.com/media-centre/press-releases/2021/covid-19-vaccine-astrazeneca-confirms-protection-against-severe-disease-hospitalisation-and-death-in-the-primary-analysis-of-phase-iii-trials.html)

[J&J](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=14a822ff-f353-49f9-a7f2-21424b201e3b)
> No hospitalizations or deaths were detected 28 days post-vaccination for 19,630 vaccinated
> individuals in the trials, compared with 16 hospitalizations reported in the placebo group
> of 19,691 individuals (incidence rate 5.2 per 1000 person-years)[160] and 7 COVID-19 related
> deaths for the same placebo group.

Fixes #837

### CODE REVIEW

**Comment by beshaya** [comment]
I have a change in flight that addresses this: https://github.com/microcovid/microcovid/pull/836

The problem with Phase III studies is they were too small to measure improvement in severe COVID, and the researchers seem to be using the wrong kind of statistical tools for calculating their CI's.

**Comment by TheSven73** [comment]
Hi Benjamin, thank you so much for the review !

> The problem with Phase III studies is they were too small to measure improvement in severe COVID, and the researchers seem to be using the wrong kind of statistical tools for calculating their CI's.

That's interesting. Given that the studies resulted in a whole bunch of zeroes, would it be fair to assume that the confidence interval includes at least the 100% value? And if so, what evidence is there to conclude that:
> we do not think that mRNA vaccines reduce the chance of hospitalization or death beyond the reduction in contracting COVID in the first place

?

In fact, would the AstraZeneca trials not indicate that the quoted assumption is too conservative? If AZ is only 60%-70% protective against mild Covid on a good day, then why did the trials show a bunch of zeroes for severe Covid? What is the probability that the zeroes are showing up by mere chance?

**Comment by beshaya** [comment]
Hi Sven,

Sure, the CI from the Phase III trials have confidence intervals that
include 100%. They also include 0%.

I call out in the new wording that we haven't done a deep dive on AZ's
vaccine. I suspect it _is_ better at preventing severe disease than any
disease, but don't have a data set that shows this. I'd perhaps guess it is
as good as the mRNA vaccines at preventing severe disease. (92% or so,
possibly as good as 99% in young healthy individuals).

**Comment by TheSven73** [comment]
Are you positive that your assessment doesn't err too much on the side of caution? If I'm not mistaken, the CDC reported 396 severe Covid cases in 77 million vaccinated individuals - that's 1 in 200,000. If the vaccinated ended up in the ICU at even 5% the unvaccinated base rate, that would raise some eyebrows, no?

**Comment by beshaya** [comment]
>Are you positive that your assessment doesn't err too much on the side of caution?

I am not sure. I've never been sure what is prudent caution and what is too much.

Let's take a look at this data...

> the CDC reported 396 severe Covid cases in 77 million vaccinated individuals - that's 1 in 200,000

That's not the right denominator, though. We'd want to know how many severe Covid cases there were per person-day and what the relative rate was for the unvaccinated population. We can make a rough estimation, though

Let's say those 77 million vaccinations were given out at a constant rate over the last 2 months. That would represent 77 million person-months.

The United States reported 5.5k hospitalizations / day over the same period. 5.5k cases / day / 300M people * 77M person * months = 55k / 300 * 77 * 31 = 43,700 cases among unvaccinated people. https://www.cdc.gov/coronavirus/2019-ncov/covid-data/covidview/index.html

Only about half of hospitalizations result in severe covid, so we'll call the number of severe cases in the unvaccinated population ~20,000. 396 / 20,000 ~= 2%, or an effectiveness vs severe disease of ~98%, 5x better than what we extracted from Israel's study.

This is a fairly naive analysis; we're not attempting to match risk profiles here - factors like age, occupation, location, etc would play a large role in risk of getting covid or severe COVID. Plus this is a super rough guess on person-months represented by the vaccinated people.

> If the vaccinated ended up in the ICU at even 5% the unvaccinated base rate, that would raise some eyebrows, no?

Looks like vaccinated people who get covid are getting severe cases at about *20%* the unvaccinated rate. I guess it didn't raise eyebrows.

Note also that hospitalization, severe, and ICU are three distinct stages of the disease; generally progressing in that order.

--

So should you 5x your budget after being vaccinated? Maybe. Honestly, everyone should set their budget to whatever they want / can agree upon with their close contacts, so long as it is less than the regional prevalence (so that you're not making your region worse).

--

There's something else that seems worth noting - if the # of cases of severe COVID in vaccinated individuals are so rare that we don't have enough statistical power to analyze the rates, maybe that should be cueing us in to not worrying about covid, regardless of exactly how the breakdown of multipliers happens.

**Comment by TheSven73** [comment]
Thank you Benjamin for the thoughtful explanation and analysis, I really appreciate it!

> Note also that hospitalization, severe, and ICU are three distinct stages of the disease; generally progressing in that order.

The numbers for the 77 million fully vaccinated people were: 5800 infected, 396 hospitalized, 74 died. I chose 396 for ease of comparison: most studies define severe covid as “hospitalization or worse”.

> effectiveness vs severe disease of ~98%, 5x better than what we extracted from Israel's study. This is a fairly naive analysis

IMHO back-of-the-envelope analyses can be extremely useful, if they help falsify a hypothesis by [an order of magnitude](https://xkcd.com/2400/). Does the result above indicate that we should, at the very least, be skeptical of the “mRNA vaccines do not reduce the chance of hospitalization or death beyond the reduction in contracting COVID in the first place” hypothesis?

What do you make of the Scottish national cohort (population-level) [study](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00677-2/fulltext) that came out a few days ago? It looked at the effect of first-dose Pfizer and AstraZeneca wrt protection against hospitalization. From where I sit, the protection 3-4 weeks post-first-dose is nothing short of astonishing, especially for a mostly elderly population.

Most surprising of all (to me) is the excellent performance of the AstraZeneca vaccine. Certainly not inferior to Pfizer when it comes to protection from hospitalization.

If the Scottish study has merit (why not?), then what evidence is there in support of:

> we do not think that mRNA vaccines reduce the chance of hospitalization or death beyond the reduction in contracting COVID in the first place

or

> It is possible that the traditional vaccines (AstraZenica, Johnson&Johnson) are somewhat more protective againt severe COVID than mild COVID, but we have not seen compelling data for this.

?

I’d like to make a case for removing these two statements altogether. This change should not encourage readers to increase their risk budget unnecessarily or even at all - because the statement about lung damage from asymptomatic covid remains in place.

**Comment by beshaya** [comment]
> What do you make of the Scottish national cohort (population-level) study
<https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)00677-2/fulltext>
that
came out a few days ago? It looked at the effect of first-dose Pfizer and
AstraZeneca wrt protection against hospitalization. From where I sit, the
protection 3-4 weeks post-first-dose is nothing short of astonishing,
especially for a mostly elderly population.

This looks like some cherry-picking of data in the "Findings" section:

Table 2 shows a 78% (71 to 83) RR for hospitalization for Pfizer-BioNTech
days 21-28 and 81% (72 to 87) for AZ. For days 42+, this drops to 77% and
59% respectively (although the AZ table has far too few participants past
42 days to say anything conclusively). But that kind of doesn't matter
since this is 1 shot efficacy and everyone is supposed to get their second
within 42 days?

They seem to have picked the best week of data to show at the top level,
hiding the significantly worse performance of other weeks in their data.

Aside, 90% risk reduction against hospitalization is already covered by 90%
reduction in incoming microCOVIDs.

**Comment by TheSven73** [comment]
> This looks like some cherry-picking of data in the "Findings" section:

> Table 2 shows a 78% (71 to 83) RR for hospitalization for Pfizer-BioNTech
> days 21-28 and 81% (72 to 87) for AZ. For days 42+, this drops to 77% and
> 59% respectively (although the AZ table has far too few participants past
> 42 days to say anything conclusively).

Cherry-picking, or disregarding results with little to no significance, ie. mostly noise? If they had wanted to cherry-pick, I guess they could have taken AZ's 91% for days 35-41.

> Aside, 90% risk reduction against hospitalization is already covered by 90% reduction in incoming microCOVIDs.

According to the microcovid calculator, single-dose AstraZeneca provides just a 44% reduction in incoming microCOVIDs.

**Comment by beshaya** [comment]
> Cherry-picking, or disregarding results with little to no significance,
ie. mostly noise? If they had wanted to cherry-pick, I guess they could
have taken AZ's 91% for days 35-41.

They picked the time window that made Pfizer's vaccine look the best. There
are certainly more opinionated ways they could have chosen to present
the data, but I still find it odd; why not do a weighted average of 28+
days?

>According to the microcovid calculator, single-dose AstraZeneca provides
just a 44% reduction in incoming microCOVIDs.

Yep, that's why I'm adding "It is possible that the traditional vaccines
(AstraZenica, Johnson&Johnson) are somewhat more protective against severe
COVID than mild COVID, but we have not seen compelling data for this."

I can change "we have not seen compelling data for this" to "we haven't
done a thorough analysis on this."

For my context, what's going on with AstraZenica doses where you are? Are
second doses being given out after 3 weeks or is a longer dosing schedule
being used? We weighted our research efforts assuming a fairly brief window
between doses (i.e. didn't spend much time diving into single dose
efficacy).

**Comment by TheSven73** [comment]
> For my context, what's going on with AstraZenica doses where you are? Are
> second doses being given out after 3 weeks or is a longer dosing schedule
> being used?

The [official NACI recommendation](https://www.canada.ca/en/public-health/services/immunization/national-advisory-committee-on-immunization-naci/extended-dose-intervals-covid-19-vaccines-early-rollout-population-protection.html#a5) says the 2nd dose can be delayed by up to 4 months. Second doses should be offered ASAP after all eligible populations have been offered first doses.

That's the theory, Next, the practice.

Here in Ontario there are currently two parallel vaccination campaigns:
- Pfizer/Moderna with limited but steady supply, in high demand (cutoff age 60 currently)
- AstraZeneca from tiny one-off "loans" (US AZ stockpile, Serum Institute before they got in trouble), very limited supply but excellent availability due to considerable AstraZeneca hesitancy in the population (cutoff age 40 currently)

For the mRNA campaign, second dose appointments are being booked 3 months out.

For AstraZeneca, no second appointments are currently being booked. I know this from personal experience. Presumably, nobody knows if AZ will be available in sufficient quantities by summer. I am seeing reports that public health authorities hope that the UK mix-and-match studies will come back positive. That would allow everyone to receive their 2nd shot using mRNA doses only.

**Comment by TheSven73** [comment]
Superseded by https://github.com/microcovid/microcovid/issues/837#issuecomment-834725033

**Pull request closed without merging**
