### PR TITLE
Fix fixed point formatting.

### PR DESCRIPTION
**Pull request by beshaya**
Closes: #341

### CODE REVIEW

**Comment by blanchardjeremy** [comment]
@beshaya  I don't know enough about this to give it a thorough code review but I can test the results. 

I guess my biggest question is: isn't there a library we could use for sug figs instead of rolling our own?

**Comment by beshaya** [comment]
> @beshaya I don't know enough about this to give it a thorough code review but I can test the results.
> 
> I guess my biggest question is: isn't there a library we could use for sug figs instead of rolling our own? Just seems like a lot of code to have around.

I spent some time looking and couldn't find anything. The combination of wanting commas and no trailing zeros seems to fall in a dead spot for javascript. Adding in the fact that I want to display numbers close to 1e6 and percents close to 100 with arbitrary precision means we either write our own display code or do a lot of fiddling with someone else's library which wasn't built with that in mind :/ 

I might be able to get it a little shorter.

**Comment by beshaya** [comment]
Took a stab at using more standard functions/libraries; the code got longer.

**Comment by blanchardjeremy** [comment]
Thanks for doing this. And thanks for adding tests.

**Pull request merged**
