### PR TITLE
Update true infections formula

### PR DESCRIPTION
**Pull request by beshaya**
- Update prevalence calculation based on 10 December 2020 Covidestim model.
- Update prevalence calculation based on COVID19 Projections' December 10 update

### CODE REVIEW

**Review by blanchardjeremy — APPROVED** [review]
LGTM

**Comment by blanchardjeremy** [comment]
FYI - relevant page - https://covid19-projections.com/estimating-true-infections-revisited/

**Comment by blanchardjeremy** [comment]
Question: Where did you get the 30 day delay (instead of 25?)

**Comment by beshaya** [comment]
For the test? The old formula was 1250 / (25 + n), and I had n set to 25.
1250 / (25 + 25) = 25. The new formula is 1000 / (10 + n). 1000 / (10 + 30)
= 25.

Easier to make one change in the test than try to track down everywhere the
prevalence would change of the projection formula changing.

**Pull request merged**
